name: Run Supabase Script

on:
  schedule:
    - cron: "0 0 */3 * *" # Cron expression to run every 3 days
  workflow_dispatch:

jobs:
  run-selenium:
    runs-on: ubuntu-latest
  
    steps:
      - shell: bash
        env:
          API_URL: ${{ secrets.API_URL }}
        run: |
          curl "%API_URL"
