name: Make request

on:
  schedule:
    - cron: "0 0 * * MON,THU" # Cron expression to run every Monday and Thursday at 12AM
  workflow_dispatch:

jobs:
  make-request:
    runs-on: ubuntu-latest
  
    steps:
      - shell: bash
        env:
          API_URL: ${{ secrets.API_URL }}
        run: |
          curl "$API_URL"
